name: Requests test

on:
  workflow_dispatch:
    inputs:
      secretKey:
        description: 'Secret Key Name'
        default: ''

jobs:
  test-job:
    name: Test job implementation
    runs-on: ubuntu-latest
    env:
      LOCATION_NAME: ${{ inputs.secretKey || 'LOCATION_IQ' }}
    steps:
      - name: Echo
        id: echo-test
        run: |
          echo ${{ secrets[format('{0}', env.LOCATION_NAME)] }}
      - name: Test using requests
        id: requests-test
        shell: python
        run: |
          import requests
          import json

          def get_test() -> None:
            url = "https://us1.locationiq.org/v1/search.php?key=${{ secrets.LOCATION_IQ }}&q=dfw&format=json"
            headers = {}
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            print(response.json())          

          def post_test() -> None:
            url = "https://jsonplaceholder.typicode.com/posts"
            payload = {
              "title": "foo",
              "body": "bar",
              "userId": 1,
            }
            headers = {}
            response = requests.post(url, headers=headers, data=json.dumps(payload))
            response.raise_for_status()
            print(response.json()) 

          def main() -> None:
            get_test()
            post_test()
            
          if __name__ == "__main__":          
            main()
