name: Test

on:
  workflow_dispatch:

jobs:
  test-job:
    name: Test job implementation
    runs-on: ubuntu-latest
    steps:
      - name: Get PR
        id: get-pr
        shell: python
        run: |
          import requests

          url = "https://us1.locationiq.org/v1/search.php?key=7822f557264c69cb711b&q=dfw&format=json"
          payload = {}
          files = {}
          headers = {}
          response = requests.request("GET", url, headers=headers, data=payload, files=files)
